# Boilerplate code generated by OVITO Pro 3.11.0
from ovito.data import *
from ovito.io import *
from ovito.modifiers import *
from ovito.pipeline import *
from ovito.qt_compat import QtCore
from ovito.vis import *

# ==== Set up pipeline ==== #

# Data import:
pipeline = import_file('tiny_nylon.data', atom_style = 'full')

# Select type:
pipeline.modifiers.append(SelectTypeModifier(types = {1}))

# ======= Set up visual elements ======= #

# Configure visual elements for pipeline
pipeline.compute().cell.vis.enabled = False
pipeline.compute().particles.vis.radius = 0.265
pipeline.compute().particles.bonds.vis.width = 0.217

# Add pipelines to scene
pipeline.add_to_scene()

# ========== Set up rendering ========== #

# Viewport setup:

from LabelWithPropertyValues import LabelWithPropertyValues

vp = Viewport()
vp.type = Viewport.Type.Perspective
vp.fov = 0.610865238198
vp.camera_dir = [0.1494272367839647, 0.0037523187482253547, -0.9887656046865307]
vp.camera_pos = [5.767820473579249, 0.652853169815129, 22.972856526208663]
vp.overlays.append(PythonViewportOverlay(
    delegate = LabelWithPropertyValues(
    use_only_selected = True, 
    outline_width = 1), 
    pipeline = pipeline))

# Rendering:
vp.render_image(filename='image.png', size=(1600, 1200))